import Image from 'next/image';
import { Icon } from '@/atoms/icon/icon';
export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div className='h-[calc(100vh-72px)] flex flex-col overflow-y-auto'>
			<div className='flex h-full overflow-y-auto pb-[72px]'>
				<section className='flex-1 flex  overflow-y-auto  justify-center items-center '>
					<div className='w-[420px] max-h-[100%]'>{children}</div>
				</section>

				<div className='flex justify-end  w-[40%] h-[98%] relative'>
					<Image
						src='/assets/onboard-img.png'
						layout='fill'
						alt='bg image'
						objectFit='cover'
					/>
				</div>
			</div>
			<footer
				className='flex border-[0.5px] border-transparent bg-white z-10 font-thin text-sm border-t-divider-gray h-[72px]
			 fixed w-full bottom-0 text-[#7a7978] px-20 items-center'
			>
				<span>&copy; 2024 The Good Thing Company. All Rights Reserved.</span>
				<span className='ml-10'>
					Why Good? | Are you an exceptional creator? | Get help
				</span>
				<div className='flex-1 flex justify-end gap-5 cursor-pointer'>
					<Icon id='instagram' />
					<Icon id='x' />
					<Icon id='fb' />
				</div>
			</footer>
		</div>
	);
}
