import Image from 'next/image';
import { Icon } from '@/atoms/icon/icon';
import OnboardFooter from '@/molecules/OnboardFooter';
export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div className='h-[calc(100vh-72px)] flex flex-col overflow-y-auto'>
			<div className='flex h-full overflow-y-auto pb-[72px] '>
				<section className='flex-1 flex  overflow-y-auto  justify-center items-center '>
					<div className='max-h-[100%]'>{children}</div>
				</section>

				<div className='flex justify-end  w-[40%] h-[98%] relative'>
					<Image
						src='/assets/onboard-img.png'
						layout='fill'
						alt='bg image'
						objectFit='cover'
					/>
				</div>
			</div>
			<OnboardFooter />
		</div>
	);
}
